### ISSUE TITLE
Fails to compile on older perls on FreeBSD 14.0-RELEASE

### ISSUE THREAD

**Issue by bingos** [Perl/version.pm#38]
FreeBSD 14.0-RELEASE ships with clang 16.0.6
`$ cc -v
FreeBSD clang version 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a259152)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
`
I noticed when doing my usual provisioning of perls for CPAN smoking, that I was seeing failure to build version.pm on some of the older perls.
Further investigation found Perls v5.10.1 to v5.18.* all failed with the following error during 'make':

>In file included from vxs.xs:18:
./vutil.c:696:24: error: incompatible pointer to integer conversion passing 'char *' to parameter of type 'long' [-Wint-conversion]
            if (LIKELY(radix)) {
                       ^~~~~
/home/cpan/pit/bare/perl-5.10.1/lib/5.10.1/amd64-freebsd/CORE/perl.h:3274:52: note: expanded from macro 'LIKELY'
#define LIKELY(cond)                        EXPECT(cond,1)
                                                   ^~~~
/home/cpan/pit/bare/perl-5.10.1/lib/5.10.1/amd64-freebsd/CORE/perl.h:3270:62: note: expanded from macro 'EXPECT'

And v5.20.0 and upwards build without errors.

I bisected against the v5.19.* development releases and found the commit that "fixes" the build error:
https://github.com/Perl/perl5/commit/6d5abc62848da0e110869e2b13c68bf498ff3a90

**Comment by Leont** [comment]
This has been fixed in 0.9931
